### ISSUE TITLE
Repo name?

### ISSUE THREAD

**Issue by jcameron** [virtualmin/virtualmin-vsftpd#1]
Shouldn't it be called virtualmin-vsftpd ?

**Comment by virtualmin** [comment]
Oops. Fixed.

**Comment by jcameron** [comment]
Thanks - can you send invites for the new repo?

**Comment by virtualmin** [comment]
It shouldn't need a new invite. You're already listed as contributor (but webmin hasn't confirmed yet).

I haven't exported this yet...I just created a bunch of them to reduce the cycling between accounts I was doing. But it'll be migrated in a day or two.
